filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_source: true
          match_source_index: 4
    json.keys_under_root: false
    json.add_error_key: true
    json.message_key: message

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      process_array: false
      max_depth: 1
      when.regexp:
        container.name: ".*ugc.*"

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  indices:
    - index: "ugc-logs-%{+yyyy.MM.dd}"
      when.regexp:
        container.name: ".*ugc.*"
    - index: "docker-logs-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
