filebeat.inputs:
  - type: filestream
    id: docker-logs
    parsers:
      - container:
          stream: all
          format: docker
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - dissect:
      field: "log.file.path"
      tokenizer: "/var/lib/docker/containers/%{container.id}/%{container.id}-json.log"
      target_prefix: ""
      ignore_failure: true
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      match_fields: ["container.id"]
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      process_array: false
      max_depth: 1
      when.regexp:
        container.image.name: "^ugc-.*"

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  indices:
    - index: "ugc-logs-%{+yyyy.MM.dd}"
      when.regexp:
        container.image.name: "^ugc-.*"
    - index: "docker-logs-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
